label = ["Account", "Industry",'Consumer', 'ERI', 'Energy Resource & chemicals', 'Financial Services', 'FS', 'LSHC', 'Life science Health care', "Sector", "sub sector","Offering portfolio","Offering","Market Offering","Leader"]


industry= ['Financial Services', 'Consumer', 'Technology, Media & Telecom',
       'Energy, Resources & Industrials', 'Life Sciences & Health Care',]

sector=['Banking & Capital Markets',
       'Transportation, Hospitality & Services', 'Insurance',
       'Technology', 'Energy & Chemicals',
       'Telecom, Media & Entertainment', 'Health Care', 'Life Sciences',
       'Automotive', 'Retail & Consumer Products',
       'Investment Management', 'Power, Utilities & Renewables',
       'Industrial Products & Construction', 'Real Estate','Holding Companies']

sub_sector=['Banking & Capital Markets', 'Transportation', 'Life and Annuity',
       'Software, Services & Platforms',
       'Chemicals & Specialty Materials', 'Health Care Providers',
       'Biopharma', 'Original Equipment Manufacturers',
       'Grocery & Convenience Stores', 'Specialty & Department Stores',
       'Asset Managers', 'Media & Entertainment',
       'Restaurants & Food Service', 'Power & Utilities', 'Med Tech',
       'Food & Beverage', 'Industrial Products',
       'Medical Wholesale & Distribution', 'Services',
       'General Insurance', 'Private Equity / Sovereign Wealth Fund',
       'Personal & Household Goods', 'Energy', 'Health Plans / Payers',
       'Mass & Discount Stores', 'Water & Waste Utilities',
       'Wholesale & Distribution', 'Hardware', 'Public Utilities',
       'Telecom', 'Sports & Live Entertainment', 'Aerospace & Defense',
       'Semiconductors', 'Agribusiness', 'Engineering & Construction',
       'Reinsurance', 'Hospitality', 'Apparel & Footwear',
       'Generics & Biosimilars', 'Automotive Suppliers', 'Airlines',
       'Mining & Metals', 'Real Estate Managers and Advisors', 'Brokers',
       'Automotive Dealers', 'Real Estate Investment Trusts',
       'Real Estate Owners', 'Auto-Tech', 'Renewable Energy',
       'Home Building', 'Trading Houses', 'Unclassified Industries',
       'Captive Finance', 'Holding Companies']

offering_portfolio=['REGULATORY & LEGAL SUPPORT', 'M&A AND RESTRUCTURING',
       'CORE BUSINESS OPERATIONS', 'ACCOUNTING & INTERNAL CONTROLS',
       'ENTERPRISE PERFORMANCE', 'HUMAN CAPITAL',
       'CUSTOMER AND MARKETING', 'STRATEGY & ANALYTICS',
       'CYBER & STRATEGIC RISK', 'TRANSACTIONS AND M&A',
       'INNOVATION & TECHNOLOGY', 'PRDA - SOFTWARE', 'CONSULTING OTHER']

offering=['FSI RISK DATA AND REGULATORY',
       'STRATEGY, DILIGENCE, & RESTRUCTURING',
       'OPERATIONS AND TECHNOLOGY TRANSFORMATION',
       'CONTROLLERSHIP, ACCOUNTING & REPORTING', 'SAP',
       'HR TRANSFORMATION', 'DISCOVERY & DATA MANAGEMENT',
       'CUSTOMER STRATEGY & APPLIED DESIGN', 'DIGITAL CONTROLS',
       'FINANCE & PERFORMANCE', 'DIGITAL CUSTOMER',
       'SUPPLY CHAIN & NETWORK OPERATIONS',
       'CORPORATE COMPLIANCE & OPERATIONAL RISK',
       'ORGANIZATION TRANSFORMATION', 'AI & DATA', 'CYBER',
       'DIGITAL FOUNDRY & OPERATIONS', 'SECURITIZATION',
       'CLOUD ENGINEERING', 'WORKFORCE TRANSFORMATION',
       'HUMAN CAPITAL AS A SERVICE', 'TEAR&I',
       'INTEGRATION AND DIVESTITURE',
       'APPLICATION MODERNIZATION & INNOVATION',
       'VALUATION, MODELING & FINANCIAL ADVISORY',
       'FORENSIC & FINANCIAL CRIME', 'INFRASTRUCTURE & CAPITAL PROJECTS',
       'STRATEGY, BRAND & REPUTATION', 'ENTERPRISE OPS AS A SERVICE',
       'CORE TECHNOLOGY OPERATIONS', 'ADV., MARKETING, & COMMERCE',
       'EXTENDED ENTERPRISE', 'ORACLE', 'INTERNAL AUDIT', 'STRATEGY',
       'EMERGING ERP SOLUTIONS', 'PLATFORMS', 'CRISIS & RESILIENCE',
       'FSI COMPLIANCE & OPERATIONAL RISK', 'TREASURY',
       'HUMAN CAPITAL PRODUCTS', 'PRDA - SOFTWARE',
       'TECHNOLOGY SERVICES OPTIMIZATION',
       'S&A HYBRID SOLUTIONS & INCUBATION',
       'STRATEGY & ANALYTICS PRODUCTS', 'CUSTOMER & MARKETING PRODUCTS',
       'ENTERPRISE PERFORMANCE PRODUCTS', 'GPS AI & DATA OPERATIONS',
       'IT & SPECIALIZED ASSURANCE', 'ASSETS & INNOVATION SERVICES',
       'CORE BUSINESS OPS PRODUCTS', 'GPS - OPERATIONS TRANSFORMATION',
       'CERTIFIED TO SELL SOLUTIONS', 'MERGERS & ACQUISITIONS PRODUCTS',
       'CORPORATE FINANCE', 'GPS DIGITAL HEALTH',
       'GPS AI & DATA ENGINEERING', 'CONSULTING OTHER',
       'ASSETS AND HYBRID BUSINESS VENTURES', 'SNET',
       'GPS - HUMAN SERVICES TRANSFORMATION', 'CORE INDUSTRY SOLUTIONS']


market_offering=['Financial Risk & Reporting', 'Strategy & Diligence',
       'Integrated Health Care', 'Operating Model / Modernization',
       'SAP Enterprise Transformation', 'HR Strategy & Solutions',
       'Contract Analytics', 'Innovation & Product Strategy',
       'Controls Advisory', 'Dynamic Finance', 'Sales Transformation',
       'Smart Factory', 'Regulatory Audit Readiness & Validation',
       'Change Services', 'AI & Insights', 'Identity Strategy',
       'Design-Led Products & Engineering DFO', 'Transactions',
       'Customer, Experience & Mktg Strategy',
       'Data Modernization & Analytics',
       'Mgd Svc-Digital Quality & Compliance', 'Future of Real Estate',
       'Service Excellence', 'Platforms & Infrastructure',
       'Workforce Development', 'HC Application Operate Services',
       'Workforce Strategy', 'Cloud Strategy, Arch & Transformation',
       'Sourcing & Procurement', 'IoT - OT - Prod Sec',
       'Digital Quality & Compliance', 'Corporate - VDD',
       'Integration & Divestiture',
       'Pricing & Commercialization Strategy', 'Workiva Controllership',
       'Application Modernization & Migration',
       'Fin Rpt Valuation \x96 MA&D', 'GPS Application Development',
       'Private Equity Investors - Buy Side',
       'Enterprise Services & Location Strategy',
       'For Distressed Proj Svcs & LIt Supp',
       'Organization Strategy and Design', 'Enterprise Risk Management',
       'Digital Commerce DFO', 'Quality Engineering', 'SAP Ops',
       'Hybrid CMS', 'Mgd Svc-Mgd Security Svc (MSS H-O)',
       'Workday Enabled Transformation',
       'Mgd Svc-Corporate Intelligence Services',
       'CFO Enterprise Strategy', 'Customer Operations',
       'AML & Sanctions Program Testing & Evals',
       'Core Infra / Zero Trust', 'Mgd Svc-Infra and Cloud',
       'Digital Commerce', 'Extended Enterprise Prgm Transformation',
       'Corporate Investigations', 'Experience Agency', 'HC Assets',
       'Strategy', 'Oracle Finance Transformation', 'SAP Controllership',
       'Strategy, Digital, & Transformation', 'Data Services',
       'Valuation Advisory-MA&D', 'Contract System Implementations',
       'Product Engineering & Development',
       'Cloud Native & Application Development', 'Managed Services',
       'Extended Enterprise MARS', 'Oracle Enterprise Transformation',
       'Marketing Technology & Operations',
       'Process Bionics and Digital Solutions', 'Business Strategy',
       'Actuarial and Insurance Solutions', 'Supply Chain Ops',
       'Application Security', 'Mgd Svc - Contract Analytics',
       'Impairment of Assets & Goodwill', 'Mgd Svc-Emerging Technology',
       'Capital Project & Bus Process Transform', 'APIs & Integration',
       'Statutory Reporting & IFRS', 'Planning & Fulfillment',
       'Tech Strategy & Business Transformation',
       'Mgd Svc-Transactional Discovery', 'Foundry Services', 'Leases',
       'Carve-Out and Divestiture Acct & Rept', 'Cyber M&A',
       'SAP/SF Enabled Transformation',
       'Digital Workforce & Workplace Solutions',
       'Retirement and Wealth Provider Transform', 'Data Operations',
       'Oracle Supply Chain Transformation', 'Emerging Sector Solutions',
       'Other Accounting & Reporting',
       'Information Technology Internal Audit',
       'Other Financial Reporting Valuation',
       'Valuation Advisory-Strategic Alternatves',
       'Other Transac Accounting & Reporting',
       'Other Tax Compliance Val-Fin Advisory', 'GPS Cloud Migration',
       'Customer Operations DFO', 'Data Privacy', 'Workday Financials',
       'Embedded PES', 'SAP Supply Chain Transformation',
       'OTT Productized Assets', 'Internal Audit Cosourcing',
       'ERP & Cloud Controls-Design & Implement', 'DCPS Resell',
       'Investment and Wealth Management', 'Resilience',
       'Controllership-Analytics', 'Program & Transformation Management',
       'Mgd Svc-Legal Management Consulting',
       'Mgd Svc-Application Security',
       'Payroll & Workforce Management Solutions',
       'Technology Asset Management', 'Enterprise Programs / ERM',
       'Identity Governance and Admin  IGA ',
       'GPS Application Operations & Maintenance', 'SOX / ICFR',
       'Insurance Transformation', 'SAP Finance Transformation', 'Infor',
       'Digital IA', 'Blackline Controllership',
       'SC&E ( ESG ) Valuation, Model & Fin Adv',
       'Treasury Transformation Services',
       'Fin Stmt & Contrl Readiness&Remediation',
       'Software License Compliance', 'Rewards & Well-Being',
       'Value Chain Optimization',
       'Detect & Respond (A/I - CSI, DRP, DAI)', 'Finance Ops',
       'Discovery Advisory', 'Process Transformation',
       'Other New Acct Standards Implement',
       'Design-Led Products & Engineering', 'Mgd Svc-Identity',
       'Readiness-Private Equity',
       'AML Trans Monitoring & Sanctions Screen', 'Product: DERA',
       'Crisis Recovery', 'Fin Rpt Valuation - MA&D',
       'Mgd Svc-EEMS: Extended Enterprise', 'FCPA Programs & Controls',
       'Digital Supply Chain Strategy', 'CTO Productized Assets',
       'Attack Surface Management',
       'Sustainability Strategy & Transformation', 'Mgd Svc-Discovery',
       'Mgd Svc-M&A Data Services', 'Mgd Svc-Finance Operate',
       'ServiceNow', 'Mgd Svc - Contract Mgt (BAU)',
       'Capital Expenditure Engineering', 'Cost & Revenue Recovery',
       'Utilities Core', 'Marketing Technology & Operations DFO',
       'HC Analytics and Insights Solutions', 'Cyber Technology & Risk',
       'Unclassified Emerging Tech', 'ConvergeHealth',
       'AI & Data Strategy', 'Digital Banking and Payments',
       'Digital Treasury', 'Anti-Fraud Programs and Controls',
       'AML Know Your Customer', 'Data & Insights',
       'AML & Sanctions Program Dev & Enhancemnt',
       'Nexus & Digital Automation', 'Corporate Intelligence Services',
       'EOaaS Productized Assets', 'Mgd Svc-SOX as a Mgd Svc',
       'Product: LeaseController Lic & Svcs', 'GPS - ReadyAI',
       'Controllership-Other Technology', 'SC&E ( ESG ) Reporting',
       'Regulatory Remediation', 'Guard.ai', 'Experience Agency DFO',
       'Digital Forensic', 'Brand & Reputation Management',
       'Commodity Trading and Risk Mgmt Sol',
       'Digital Trust & Online Protection',
       'Software Licenses & Maintenance',
       'AML Risk Assessment & Customer Risk Rate',
       'Oracle Enabled Transformation',
       'Restructuring & Value Creation Services',
       'Tangible Asset Val & Consultg- MA&D', 'Service Excellence DFO',
       'Emerging Reg Strategy & Business Integr', 'FCPA Investigations',
       'Other Attestations, Assessments, & AUP',
       'Governance, Risk, and Assurance',
       'Close Consolidate & Report (A/I)',
       'Working Capital and Liquidity Services', 'Cyber Cloud',
       'Cust/Cons Identity & Access Mgmt (CIAM)',
       'Data Governance & Protection', 'Strategic Risk Consulting',
       'Compliance Program Strategy & Design', 'M&A Central - SaaS',
       'AI & Modeling', 'Sales Transformation DFO', 'Audit and Reviews',
       'Tax Valuation- MA&D', 'Corporate - Buy Side', 'Company Advisory',
       'Ext Enterprise Ecosystem Ops Center ESOC',
       'Compliance Service Delivery', 'IT Ops',
       'GPS Strategic Transformation', 'Product Quality and Safety',
       'As-a-Service and New Business Incubation',
       'Modeling Advisory-Strategic Alternatives',
       'Oracle Controllership', 'TPA Readiness and Advisory',
       'Mgd Svc-Third Party', 'Product: ValueD Lic & Svcs',
       'SC&E ( ESG ) Internal Audit', 'Oracle Ops',
       'Arbitration & Dispute Consulting',
       'Real Estate Asset Valuation & Consulting',
       'Regulatory Cost Recovery', 'SC&E ( ESG ) Extended Enterprise',
       'SC&E (“ESG”) Internal Audit',
       'Real Estate Val & Consulting- MA&D', 'Product: Convergence/ACADA',
       'Modeling Advisory - MA&D', 'Product: Accelsior Lic & Svcs',
       'Cyber Program Transformation', 'Regulated Revenue Solutions',
       'Mgd Svc-Document Review Services',
       'Adversary Pursuit & Incident Response',
       'Mgd Svc-Commodity Trading Operate', 'Readiness - Corporate',
       'SC&E (“ESG”) Reporting',
       'Pricing & Commercialization Strategy DFO',
       'Crisis Response Services', 'Emerging Identity Services',
       'HC Managed Capabilities as a Service',
       'Purchase Accounting & Reporting', 'SOC Report Attestations',
       'Other Emerging Solutions',
       'Tax & Financial Reporting Valuation MA&D',
       'GPS - Operations and Innovation', 'Project Delivery',
       'Commercial Litigation', 'Lease Advisory',
       'Private Equity Investors - VDD', 'CtS Solution Other',
       'Business Entity Transformation', 'GPS Quant Risk Mgt Services',
       'Asset Lifecycle Management', 'Finance Separation',
       'Mgd Svcs Continuous Monitoring Solutions',
       'DCF Service Offering 1', 'Product: Solvas Digitize Lic & Svcs',
       'Other', 'Advanced Connectivity', 'Finance Integration',
       'Portfolio Valuation Services', 'Risk & Control',
       '3rd Party Resale', 'Treasury M&A Services',
       'Bankruptcy Administration Services', 'DAAP', 'MyCloud ERP',
       'Access and Adv Auth', 'ERP Microsoft Dynamics',
       'CSP Identity and Directory Services', 'Mgd Svc-Data Remediation',
       'GPS Health Transformation', 'Sustainability Platforms',
       'TSO Productized Assets', 'GPS - Data Modernization & Analytics',
       'Consumer Svcs Transparency&Protection',
       'GPS Reg Gov and Compliance', 'Mgd Svc-Program Integrity',
       'Secure Supply Chain', 'Controls Transformation',
       'Claims Management Services',
       'GPS - Emerging Infrastructure Platforms',
       'Accounting & SEC Reporting - Corporate',
       'Wargaming, Board & Labs', 'GPS Digital Engineering',
       'Business Insurance Claims Consulting',
       'GPS - Business of Tech Transformation',
       'Cognitive Spend Insights (CSI)',
       'GPS Mission & Business Strategy',
       'AML Technology and Model Validation', 'Technology Enablement',
       'Product: Solvas | AM Lic & Svcs',
       'Legal - Information Governance', 'Creditor Advisory',
       'non-MS&P Program Integrity', 'ESG Compliance and Strategies',
       'GPS - Energy, Climate, Natural Resources', 'DMAP Clearlight',
       'MarketPoint Services', 'Cross Border Strategies - Buy Side',
       'Product: MarketPoint Licenses', 'SCNO Productized Assets',
       'Mgd Svc-DataMaaP', 'Mgd Svc-LeaseMARC',
       'ConvergeHealth Safety Product', 'FCPA Due Diligence',
       'Mgd Svc-Mgd Extnd Detc & Res (MXDR)', 'AMI Productized Assets',
       'DNU-Inveritas', 'Information Governance - Technology',
       'Deloitte Pixel', 'Mgd Svc- Relativity As A Platform',
       'Third Party Risk Management', 'DNU-innoWake', 'Product: ECM',
       'ConvergeHealth Safety Services', 'S&A Productized Assets',
       'DCPS Resell Cloud Consumption', 'Cyber Analytics & Emerging AI',
       'Product: MRMS/LIBOR/ACADA', 'Converged Security',
       'DCF Service Offering 7', 'Detect & Respond (A/I – CSI, DRP, DAI)',
       'GPS Program Management and Realization',
       'Privledged Account Management (PAM)', 'CE Productized Assets',
       'Oracle Retail Transformation', 'Advisory',
       'F&EP Productized Assets', 'PredictRisk', 'C&M Productized Assets',
       'Oracle Productized Assets',
       'Digital Insights & Analytics | Treasury',
       'Product: Solvas | Banking Lic & Svcs',
       'Smart Manufacturing Platform',
       'GPS Process Bionics & Digital Solutions',
       'DCF Service Offering 4', 'SNET-Customer Solutions',
       'IP Development & Monetization',
       'SC&E ( ESG ) Strategy Brand & Reputation',
       'GPS HS Program Analytics', 'GPS Credit & Fin Risk Adv Services',
       'Mission Cyber', 'SC&E ( ESG ) Crisis & Resilience',
       'GPS - AI Insights & Engagement',
       'GPS - Transportation Modernization', 'GPS Health Connect',
       'Fairness Opinions', 'SNET-SAP', 'CortexAI',
       'SC&E (“ESG”) Strategy Brand & Reputation', 'MissionGraph',
       'GPS - Data Operations', 'Mgd Svc- Communication Surveillance',
       'GPS Mission-IT Alignment', 'Mgd Svc- Breach Response',
       'Emerg ERP Solutions Productized Assets', 'Health360 - SaaS',
       'Accounting & Reporting Resale',
       'Audit Review Support - FAA and IAP', 'SNET-Cloud Hosting',
       'SNET-IM/Analytics', 'Accounting &SEC Reporting-Private Equity',
       'Reimagine Cold Chain - SaaS', 'DCF Service Offering 2',
       'DCF Service Offering 3', 'Fresh Start Accounting',
       'CentralSight - SW', 'SAP Productized Assets',
       'Product: Other Prog Int Products',
       'DNU-CH Connect for Healthcare - SW',
       'CH Connect for Public Sector - SW',
       'GPS Eligibility & Enrollment', 'M&A Central - SW',
       'SC&E (“ESG”) Extended Enterprise', 'SNET-Oracle',
       'CentralSight - SaaS', 'Reimagine Cold Chain - SW']

labels = label+market_offering+offering+offering_portfolio+sector+sub_sector+market_offering+industry